### ISSUE TITLE
Reverse proxy generic function

### ISSUE THREAD

**Issue by TurpinA** [GuillaumeBchd/Styx#3]
## Is your feature request related to a problem? Please describe.
We would like to be able to create a unknown number of routes generated from a configuration file. 

## Describe the solution you'd like
To do that we should have a generic function to create a reverse proxy link. We might be able to handle the load balancer in this function too but it's not a priority right now.

We could use a Struct that holds all the informations from the configuration file. It would probably look like this :
```go
type Route struct {
    Name string,
    Entrypoint string,
    Destinations []string
}
```

This struct should be given to a generator that will creates a simple Handler that we will add to our router.

## Describe alternatives you've considered
A new package that handles the creation of theses routes.

## Additional context
Since it's one of the first issue it's probably in this branch that we will implements the base of our router and the basic architecture of our project.

**Comment by gbchd** [comment]
I started working on the package rvp. 

You can check out the branch [generic-rvp-func](https://github.com/GuillaumeBchd/Styx/tree/generic-rvp-func).

It might be needed to revisit it later to add some functionnality or make it more perfomant for a real-time usage.
