### ISSUE TITLE
Mettre en place les tests de performances

### ISSUE THREAD

**Issue by TurpinA** [GuillaumeBchd/Styx#4]
Mettre en place un outil permettant de faire des mesures de performances de notre reverse-proxy.
Ces mesures se feront principalement sur les temps que mettent nos requêtes.
Pour cela nous pouvons utiliser un outil déjà existant :

[WRK - Benchmarking](https://github.com/wg/wrk)

**Comment by AdrienVerdier** [comment]
COUCOU
